name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  # Avoid noisy outputs like "tput: No value for $TERM and no -T specified"
  TERM: dumb

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make bin

      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with: 
        path: "kompose"
